#!/usr/bin/env bash
# One-shot install for auto_zgate_edge_tunnel_build_bot on Ubuntu 24.04.
# Prompts for Telegram bot name, token, and optional sudo password (no defaults in repo).
# Copyright (c) eCloudseal Inc.  All rights reserved.  Author: Lai Hou Chang (James Lai)
set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_USER="${SUDO_USER:-${USER:-$(whoami)}}"

if [[ "$(id -u)" -ne 0 ]]; then
    echo "請使用 sudo 執行此安裝腳本，例如: sudo ./install.sh"
    exit 1
fi

echo "=== auto_zgate_edge_tunnel_build_bot 安裝 ==="
echo "安裝目錄: ${INSTALL_DIR}"
echo "執行服務的使用者: ${RUN_USER}"
echo ""

# Install system dependencies
echo ">>> 安裝系統套件 (curl, jq, python3)..."
apt-get update -qq
apt-get install -y curl jq python3

# Directories and permissions (state/ and latest_version/ must be writable by RUN_USER for Telegram bot and run_build.sh)
echo ">>> 建立 state 目錄與腳本權限..."
mkdir -p "${INSTALL_DIR}/state"
[[ -d "${INSTALL_DIR}/latest_version" ]] || mkdir -p "${INSTALL_DIR}/latest_version"
chown -R "${RUN_USER}:${RUN_USER}" "${INSTALL_DIR}/state" "${INSTALL_DIR}/latest_version" 2>/dev/null || true
chmod +x "${INSTALL_DIR}/bin/check_and_build.sh" "${INSTALL_DIR}/bin/run_build.sh" 2>/dev/null || true

# Interactive .env setup (no default secrets in repo)
ENV_FILE="${INSTALL_DIR}/.env"
if [[ -f "${ENV_FILE}" ]]; then
    read -p ".env 已存在，是否覆寫並重新輸入設定？(y/N): " OVERWRITE
    if [[ "${OVERWRITE,,}" != "y" && "${OVERWRITE,,}" != "yes" ]]; then
        echo "保留既有 .env，跳過設定詢問。"
    else
        rm -f "${ENV_FILE}"
    fi
fi

if [[ ! -f "${ENV_FILE}" ]]; then
    echo ""
    echo ">>> 請輸入 Telegram 與建置環境設定（不寫入版控，僅存於本機 .env）："
    read -p "Telegram 機器人名稱 (選填，僅供顯示): " TELEGRAM_BOT_NAME
    read -p "Telegram Bot Token (必填，由 @BotFather 取得): " TELEGRAM_TOKEN
    read -sp "預設 sudo 密碼 (選填，AWS EC2 等非互動建置用；直接 Enter 略過): " SUDO_PASS
    echo ""

    if [[ -z "${TELEGRAM_TOKEN:-}" ]]; then
        echo "錯誤：Telegram Bot Token 為必填。請重新執行 install.sh 或手動編輯 .env。"
        exit 1
    fi

    {
        echo "# Generated by install.sh; do not commit."
        echo "TELEGRAM_TOKEN=${TELEGRAM_TOKEN}"
        [[ -n "${TELEGRAM_BOT_NAME:-}" ]] && echo "TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}"
        [[ -n "${SUDO_PASS:-}" ]] && echo "SUDO_PASS=${SUDO_PASS}"
    } > "${ENV_FILE}"
    chown "${RUN_USER}:${RUN_USER}" "${ENV_FILE}" 2>/dev/null || true
    chmod 600 "${ENV_FILE}"
    echo "已寫入 .env。"
fi

# systemd: replace hardcoded path and user
echo ">>> 安裝 systemd 服務..."
OLD_PATH="/home/zgate/auto_zgate_edge_tunnel_build_bot"
for unit in auto_zgate_edge_tunnel_build_bot.service auto_zgate_edge_tunnel_build_bot.timer auto_zgate_edge_tunnel_build_bot_telegram.service; do
    src="${INSTALL_DIR}/systemd/${unit}"
    dst="/etc/systemd/system/${unit}"
    if [[ -f "${src}" ]]; then
        sed -e "s|${OLD_PATH}|${INSTALL_DIR}|g" -e "s|User=zgate|User=${RUN_USER}|g" "${src}" > "${dst}"
        echo "  已安裝 ${unit}"
    fi
done

# Reload and enable
echo ">>> 啟用並啟動服務..."
systemctl daemon-reload
systemctl enable --now auto_zgate_edge_tunnel_build_bot.timer
systemctl enable --now auto_zgate_edge_tunnel_build_bot_telegram.service

echo ""
echo "=== 安裝完成 ==="
echo "安裝目錄: ${INSTALL_DIR}"
echo "服務使用者: ${RUN_USER}"
echo ""
echo "檢查狀態:"
echo "  systemctl status auto_zgate_edge_tunnel_build_bot.timer"
echo "  systemctl status auto_zgate_edge_tunnel_build_bot_telegram.service"
echo "  systemctl list-timers --all | grep zgate"
echo ""
echo "若曾略過 Token 設定，請編輯 .env 填入 TELEGRAM_TOKEN 後執行:"
echo "  sudo systemctl restart auto_zgate_edge_tunnel_build_bot_telegram"
echo ""
